services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - .:/var/www/html:delegated

  mysql:
    image: mysql:8.2
    ports:
      - '4306:3306'
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - .:/var/www/html